openapi: 3.0.2

info:
  version:     1.2.1
  title:       Schoolbox API
  description: |
    This document describes the API endpoints that are available to a Schoolbox
    instance.

    This document is current as of Schoolbox version 22.0.0.
  x-api-id:    0609d493-8804-4e97-b5ac-0ed7b3c99db8
  x-audience:  external-partner
  contact:
    name:  Schoolbox Team
    url:   https://schoolbox.com.au
    email: developers@schoolbox.com.au
  x-logo:
    url: './logo.png'

tags:
  - name: session
    x-displayName: Session management
    description: |
      Authenticate and create sessions for users.

  - name: file
    x-displayName: File management
    description: |
      Upload files.

  - name: user
    x-displayName: Users
    description: |
      Create and manage users.

  - name: discussion
    x-displayName: Discussions
    description: |
      Create and manage discussion threads and comments.

  - name: mobile
    x-displayName: Push Notification
    description: Endpoints for Mobile App Developers to connect and register devices

  - name: news
    x-displayName: News
    description: |
      Create and manage school news (also known as communications).

  - name: assessment
    x-displayName: Assessment
    description: |
      Search and extract assessment information including results.

servers:
  - url: https://{hostname}.{domain}/
    variables:
      hostname:
        description: The subdomain of the school's domain name on which Schoolbox is hosted.
        default: demo
      domain:
        description: The school's domain name.
        default: schoolbox.com.au

paths:

  /user:
    $ref: 'paths/user.yaml'

  /user/token:
    $ref: 'paths/user@token.yaml'

  /user/token/{id}:
    $ref: 'paths/user@token@{id}.yaml'

  /user/{id}:
    $ref: 'paths/user@{id}.yaml'

  /user/{id}/group:
    $ref: 'paths/user@{id}@groupMembership.yaml'

  /user/{id}/group/{groupId}:
    $ref: 'paths/user@{id}@groupMembership@{groupId}.yaml'

  /discussion/{contextType}/{contextId}/comments/{id}:
    $ref: 'paths/discussion@{contextType}@{contextId}@comments@{id}.yaml'

  /discussion/{contextType}/{contextId}/comments/{id}/comments:
    $ref: 'paths/discussion@{contextType}@{contextId}@comments@{id}@comments.yaml'

  /discussion/{contextType}/{contextId}/threads/{id}:
    $ref: 'paths/discussion@{contextType}@{contextId}@threads@{id}.yaml'

  /discussion/{contextType}/{contextId}/threads:
    $ref: 'paths/discussion@{contextType}@{contextId}@threads.yaml'

  /discussion/{contextType}/{contextId}/threads/{id}/comments:
    $ref: 'paths/discussion@{contextType}@{contextId}@threads@{id}@comments.yaml'

  /discussion/{contextType}/{contextId}/threads/{id}/open:
    $ref: 'paths/discussion@{contextType}@{contextId}@threads@{id}@open.yaml'

  /discussion/{contextType}/{contextId}/threads/{id}/close:
    $ref: 'paths/discussion@{contextType}@{contextId}@threads@{id}@close.yaml'

  /api/session:
    $ref: 'paths/api@session.yaml'

  /api/register/{provider}:
    $ref: 'paths/api@register@{provider}.yaml'

  /storage/asyncUpload.php:
    $ref: 'paths/storage@asyncUpload.php.yaml'

  /news/create:
    $ref: 'paths/news@create.yaml'

  /news/topics:
    $ref: 'paths/news@topics.yaml'

  /news/{id}:
    $ref: 'paths/news@{id}.yaml'

  /news/{id}/delete:
    $ref: 'paths/news@{id}@delete.yaml'

  /news/moderation/{id}/{status}:
    $ref: 'paths/news@moderation@{id}@{status}.yaml'

  /news/saved/:
    $ref: 'paths/news@saved.yaml'

  /news/saved/{id}/add:
    $ref: 'paths/news@saved@{id}@add.yaml'

  /news/saved/{id}/remove:
    $ref: 'paths/news@saved@{id}@remove.yaml'

  /news/me/articles:
    $ref: 'paths/news@me@articles.yaml'

  /news/lists/feed:
    $ref: 'paths/news@lists@feed.yaml'

  /news/feed/{key}:
    $ref: 'paths/news@feed@{key}.yaml'

  /news/lists/folder/{id}:
    $ref: 'paths/news@lists@folder@{id}.yaml'

  /api/assessment/{id}:
    $ref: 'paths/assessments@{id}.yaml'

security:
  # Authorization is handled by Schoolbox itself once a user is authenticated:
  # therefore, no scopes are defined for any security scheme.
  - session: []
  - bearerAuth: []

components:
  securitySchemes:
    session:
      $ref: components/securitySchemes/session.yaml
    bearerAuth:
      $ref: components/securitySchemes/bearerAuth.yaml
